// src/components/sidebar/sidebar-button.tsx
import type { SidebarButtonProps } from "./types";

const SidebarButton = ({
  children,
  expanded = true,
  Icon,
  onClick,
}: SidebarButtonProps) => {
  return (
    <button
      className="flex h-10 w-full cursor-pointer flex-row items-center gap-2 rounded-md p-2 text-start font-medium hover:bg-slate-800/40"
      onClick={onClick}
    >
      <Icon className="h-5 w-5" />
      {expanded && children}
    </button>
  );
};

export default SidebarButton;

// apps/svelte/src/lib/components/sidebar/sidebar-button.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { page } from '$app/stores';

	export let href: string;
	export let Icon: any | null = null;

	$: currentRoute = $page.url.pathname;
</script>

<a
	class={cn(
		'flex items-center gap-2 rounded-md px-2 py-1 text-sm font-medium',
		currentRoute === href && 'bg-muted-foreground/10'
	)}
	{href}
>
	{#if Icon}
		<Icon class="size-4 opacity-70" />
	{/if}
	<span>Schedule</span>
</a>
